### ISSUE TITLE
ps_out plotting not working in embedded python

### ISSUE THREAD

**Issue by woutersj** [texmacs/python#1]
Plotting with matplotlib fails for me in TeXmacs 1.99.11 on Fedora 31. I can plot in a session, but not in embedded code (inserted via Insert -> Fold -> Executable -> Python).
The ps_out(fig) command results in the contents of the ps plot being printed on screen, followed by

```
\x5Traceback (most recent call last):
  File "<string>", line 1
    import matplotlib
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
RecursionError: maximum recursion depth exceeded
```

**Comment by sadhen** [comment]
Thanks for your report. I will fix it as soon as possible.

**Comment by sadhen** [comment]
@woutersj 

It seems the current implementation of python embedded  code does not support `ps_out`.

The output of the embedded code is the output generated by python.

<img width="193" alt="截屏2019-12-14上午9 46 38" src="https://user-images.githubusercontent.com/1267865/70841593-a4da1d80-1e56-11ea-9e78-e6db127d8a0c.png">

<img width="102" alt="截屏2019-12-14上午9 47 24" src="https://user-images.githubusercontent.com/1267865/70841608-bf13fb80-1e56-11ea-8684-6793faeebbaf.png">

**Comment by woutersj** [comment]
Oddly enough, plotting from embedded SageMath does work, even though it is also Python based.

**Comment by woutersj** [comment]
This works again now, using the TeXmacs git version 0db2a1f2245dda0e65ea82c2ac6a6f33d3401330 with Python 3.9 on Fedora 33. Thanks a lot for the great plugin!
